quitOnTopLevelReturn: true
os:
  openPreset: 'nvim-remote'
  editPreset: 'nvim-remote'
  edit: 'nvim-remote'
  mergeTool: 'nvim -d'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  diffCommand: "git --no-pager diff --color=always --minimal"
gui:
  theme:
    activeBorderColor:
      - '#89B4FA'
    inactiveBorderColor:
      - '#585B70'
    selectedLineBgColor:
      - '#45475A'
    cherryPickedCommitBgColor:
      - '#F38BA8'
    cherryPickedCommitFgColor:
      - '#1E1E2E'
  nerdFontsVersion: 3
  showIcons: true
